apiVersion: v1
kind: Namespace
metadata:
  name: soft-limits
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: soft-limits
  namespace: soft-limits
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: soft-limits
  namespace: soft-limits
  labels:
    app: soft-limits
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: soft-limits
    spec:
      serviceAccountName: soft-limits
      containers:
      - name: soft-limits
        image: beenverifiedinc/soft-limits:latest
        args:
        - -interval=15
        resources:
          limits:
            cpu: 15m
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 20Mi
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: soft-limits
  namespace: soft-limits
  labels:
    app: soft-limits
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: soft-limits
  namespace: kube-system
  labels:
    app: soft-limits
rules:
- apiGroups:
  - ""
  resources:
  - services/proxy
  resourceNames:
  - "http:heapster:"
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: soft-limits
  namespace: kube-system
  labels:
    app: soft-limits
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: soft-limits
subjects:
- kind: ServiceAccount
  name: soft-limits
  namespace: soft-limits
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: soft-limits
  namespace: soft-limits
  labels:
    app: soft-limits
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: soft-limits
subjects:
- kind: ServiceAccount
  name: soft-limits
  namespace: soft-limits
